// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pepwximoaoqkqultuvzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcHd4aW1vYW9xa3F1bHR1dnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODU2NzQsImV4cCI6MjA2NjA2MTY3NH0.RoblLUYrZ03tUVTEqTwkuahTpMT6tWV1HKTqLfX_D-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);